//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeotekMetallCompleteDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActsOfWork
    {
        public int ActID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<System.DateTime> ActDate { get; set; }
        public byte[] FilePath { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
