//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeotekMetallCompleteDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStageUsers
    {
        public int ID { get; set; }
        public int StageID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ProjectStages ProjectStages { get; set; }
        public virtual Users Users { get; set; }
    }
}
