//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeotekMetallCompleteDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public int RequestID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ObjectName { get; set; }
        public string Address { get; set; }
        public decimal Area { get; set; }
        public Nullable<int> Floors { get; set; }
        public string ObjectType { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> RoomCount { get; set; }
        public string WorkType { get; set; }
        public string Description { get; set; }
        public System.DateTime Deadline { get; set; }
        public string ApprovalReason { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projects> Projects { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
