//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeotekMetallCompleteDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskReportFiles
    {
        public int FileID { get; set; }
        public int ReportID { get; set; }
        public byte[] FilePath { get; set; }
        public string FileType { get; set; }
    
        public virtual TaskReports TaskReports { get; set; }
    }
}
