//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeotekMetallCompleteDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskReports
    {
        public int ReportID { get; set; }
        public int TaskID { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }
        public string Description { get; set; }
        public System.DateTime UploadDate { get; set; }
    
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
    }
}
