//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeotekMetallCompleteDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskReports()
        {
            this.TaskReportFiles = new HashSet<TaskReportFiles>();
        }
    
        public int ReportID { get; set; }
        public int TaskID { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public string Description { get; set; }
        public System.DateTime UploadDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskReportFiles> TaskReportFiles { get; set; }
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
    }
}
